# Generated by Django 5.0.6 on 2024-06-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='This is the default, title change it in profile', max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('birth_date', models.DateField(blank=True, default='2000-05-20', null=True)),
                ('address', models.TextField(blank=True, default='Add Address', max_length=250, null=True)),
                ('city', models.CharField(blank=True, default='Add Address', max_length=250, null=True)),
                ('Landmark', models.CharField(blank=True, default='Add Address', max_length=250, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='static/pngwing.com (22).png', null=True, upload_to='users/')),
                ('Gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (3, 'others')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
