# Generated by Django 5.0.6 on 2024-06-26 11:06

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapp', '0009_alter_chatgroup_group_name_privatechat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=500, unique=True),
        ),
    ]
