# Generated by Django 5.0.6 on 2024-06-28 15:15

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapp', '0024_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='unread_messages_count',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=500, unique=True),
        ),
    ]
